### ISSUE TITLE
Присваивание значения суммы пополнения вместо увеличения баланса  в методе add(int amount)

### ISSUE THREAD

**Issue by Spider-Dad** [Spider-Dad/javaqa_team_diplom_2#1]
## Описание

В методе `add(int amount`) класса `SavingAccount` обнаружена ошибка в логике. Вместо увеличения баланса на сумму пополнения, происходит присваивание значения суммы пополнения самому балансу. Это приводит к неправильному результату, где баланс счета становится равным сумме пополнения, а не увеличивается на эту сумму.

## Локация дефекта

https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

## Шаги воспроизведения 

1. Создать экземпляр класса `SavingAccount` с начальным балансом `2_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод `add(int amount)` с заданной суммой пополнения `3_000`.
3. Проверить результат пополнения счета и значение баланса счета.

_Ожидаемый результат:_ метод `add(int amount)` должен увеличить баланс счета на заданную сумму пополнения. Значение баланса счета после пополнения должно быть равно `5_000`

_Фактический результат:_ вместо увеличения баланса на сумму пополнения счета, присваивается значение суммы пополнения самому балансу. Это приводит к неправильному значению баланса, которое становится равным `3_000`

##  Тест

https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L20

## Окружение
-  Операционная система: Windows 11
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
@OndineVIP посмотри этот ussue

**Comment by OndineVIP** [comment]
В методе `add` нужно изменить строку `balance = amount;` на `balance += amount;`, чтобы при пополнении баланса сумма добавлялась к текущему балансу, а не заменяла его. Вот правильный код:
```
/**
 * Операция пополнения карты на указанную сумму.
 * В результате успешного вызова этого метода, баланс должен увеличиться
 * на сумму покупки. Если же операция может привести к некорректному
 * состоянию счёта, то операция должна
 * завершиться вернув false и ничего не поменяв на счёте.
 * @param amount - сумма пополнения
 * @return true если операция прошла успешно, false иначе.
 * @param amount
 * @return
 */
@Override
public boolean add(int amount) {
    if (amount <= 0) {
        return false;
    }
    if (balance + amount < maxBalance) {
        balance += amount;
        return true;
    } else {
        return false;
    }
}
