### ISSUE TITLE
Не выдает ошибку при покупке с превышением лимита в  классе CreditAccount  

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#10]
**Описание:**
В методе account.pay класса CreditAccount при покупке с превышением лимита в  классе CreditAccount  не выдает ошибку. По условиям данная операция невозможна. 

**Локация дефекта:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

**Шаги воспроизведения**
1.Создать экземпляр класса CreditAccount с начальным балансом 10_000, кредитным лимитом 15_000 , сумма покупки  25_000.
2.Вызвать метод account.pay(int amount) с заданной суммой в 25_000.
3.Проверить результат пополнения суммы  основного баланса.

**Ожидаемый результат:** 
метод account.pay(int amount) должен не пропустить операцию тк по условию нельзя оплачивать суммы которые превышают лимит.

**Фактический результат**:
ошибка на запрет операции не срабатывает
 
**Тест:**

    @Test
    public void testCreditLimitExceeded() {
        int initialBalance = 10_000;
        int creditLimit = 15_000;
        int amount = 25000;

        CreditAccount account = new CreditAccount(initialBalance, creditLimit, 10);

        boolean result = account.pay(25000);
        assertFalse(result);
        assertEquals(10000, account.getBalance());
    }

  **Окружение:** 
  Операционная система: 
- Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
Дефект в методе `pay()` класса `CreditAccount`:
После проверки на превышение кредитного лимита необходимо добавить  исключение `IllegalStateException`, которое будет выбрасывать сообщение при попытке совершить покупку превышающую кредитный лимит.
Добавление ислючения `IllegalStateException` в метод влечет за собой изменение теста, а именно применения `assertThrows` для проверки выбрасывания исключения. 
```
//        boolean result = account.pay(amount);
//        assertFalse(result);
        assertThrows(IllegalStateException.class, () -> account.pay(amount));
        assertEquals(10_000, account.getBalance());
    }
```


Для корректной проверки выброса исключения следуют сразу же исправить дефект указанный issue #11  на проверку превышение кредитного лимита в методе pay().
В исходном коде метода идет проверка начального баланса без уменьшения на сумму покупки.
Вместо `if (balance > -creditLimit)` следует указать `if (balance -amount> -creditLimit)
