### ISSUE TITLE
Не выдает ошибку при покупке с недостаточным балансом в классе CreditAccount

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#11]
**Описание:**
В методе account.pay класса CreditAccount при покупке с недостаточным балансом  в  классе CreditAccount  не выдает ошибку. По условиям данная операция невозможна. 

**Локация дефекта:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

**Шаги воспроизведения:**
1.Создать экземпляр класса CreditAccount с начальным балансом 10_000, кредитным лимитом 10_000 , сумма покупки  11_000.
2.Вызвать метод account.pay(int amount) с заданной суммой в 11_000.
3.Проверить результат пополнения суммы  основного баланса.

**Ожидаемый результат:** 
метод account.pay(int amount) должен не пропустить операцию тк по условию нельзя оплачивать суммы которые превышают лимит.

**Фактический результат**:
ошибка на запрет операции не срабатывает
 
**Тест:**

        @Test
    public void testPauTheBillInsufficientFunds() {
        int initialBalance = 10_000;
        int creditLimit = 1000;
        int amount = 11000;
        CreditAccount account = new CreditAccount(initialBalance, creditLimit, 10);
        boolean result = account.pay(11000);
        assertFalse(result);
        assertEquals(10000, account.getBalance());
    }

  
   
 **Окружение:**
 Операционная система: 

- Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
Решено в issue #10 
Дефект в методе `pay()`  класса `CreditAccount`
При проверке на превышение кредитного лимита проверялся начальный баланс, а не баланс уменьшенный на сумму покупки.
Вместо `if (balance > -creditLimit)` следует указать `if (balance -amount> -creditLimit)`
