### ISSUE TITLE
Не выдает ошибку при покупке с отрицательным балансом в классе CreditAccount 

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#12]
**Описание:**
В методе account.pay класса CreditAccount при покупке с отрицательным балансом в  классе CreditAccount  не выдает ошибку. По условиям данная операция невозможна. 

**Локация дефекта:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

**Шаги воспроизведения:**
1.Создать экземпляр класса CreditAccount с начальным балансом -10_000, кредитным лимитом 1000 .
2.Вызвать метод account.pay(int amount) с заданной суммой в 200.
3.Проверить результат пополнения суммы  основного баланса.

**Ожидаемый результат:** 
метод account.pay(int amount) должен не пропустить операцию тк по условию нельзя оплачивать суммы которые превышают лимит.

**Фактический результат**:
ошибка на запрет операции не срабатывает.
 
**Тест:**

    @Test
    public void testPayTheBillNegativeBalance() {
        int initialBalance = -10_000;
        int creditLimit = 1000;

        CreditAccount account = new CreditAccount(initialBalance, creditLimit, 10);

        boolean result = account.pay(200);
        assertFalse(result);
        assertEquals(10000, account.getBalance());
    }
    
   

 **Окружение:**
 Операционная система: 

- Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
Согласно требованиям начальный баланс не может быть отрицательным.
Необходимо:
1.  В методе `CreditAccount` добавить исключение `IllegalArgumentException` на отрицательное значение:
```
if (initialBalance < 0) {
            throw new IllegalArgumentException(
                    "Начальный баланс не может быть отрицательным, а у вас: " + initialBalance
            );
```
2. Изменить тестовый  метод `testPayTheBillNegativeBalance()`  на проверку выброса  исключения:
```
@Test
    public void testPayTheBillNegativeBalance() { // issue #12
        assertThrows(IllegalArgumentException.class, () -> {
            int initialBalance = -10_000;
            int creditLimit = 1000;

            new CreditAccount(initialBalance, creditLimit, 10);
        });
        
    }
```
