### ISSUE TITLE
В классе CreditAccount  не хватает ставки процента, для расчета годового изменения. 

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#13]
**Описание:**
В методе  yearChange в классе CreditAccount уравнение написано не полностью, в нем не хватает ставки процента для расчета нужных данных. 

**Локация дефекта:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

**Шаги воспроизведения:**
1.Создать экземпляр класса CreditAccount с начальным балансом -200, кредитным лимитом 15 .
2. Вызвать account.yearChange.

**Ожидаемый результат:** 
Ожидаемый результат должен получиться -30

**Фактический результат**:
Тест не проходит. 
 
**Тест:**

      @Test
    public void testYearChangeNegativeBalance() {
        CreditAccount account = new CreditAccount(-200, 15, 0);
        assertEquals(-30, account.yearChange());
    
   

 **Окружение:**
Операционная система:

- Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
Дефект метода `yearChange()` класса `CreditAccount`:
Метод неправильно вычисляет сумму процентов на отрицательный баланс. Вместо этого, он делит баланс на 100, а затем умножает на ставку. Однако, чтобы вычислить проценты отрицательного значения, следует использовать абсолютное значение баланса. Правильная реализация должна быть:
```
     public int yearChange() {
        if (balance < 0) {
            return (-balance / 100) * rate; 
        } else {
            return 0;
        }
    }
```
В тестовый метод также внесены изменения, согласно требования, начальный баланс не может быть отрицаетльный. Отрицаетльный текущий баланс необхолимо реализовать через метод `pay()`. Правильная реализация тестового метода:
```
   account = new CreditAccount(0,300,15);
        account.pay(200); // Покупка для отрицательного баланса
        assertEquals(30, account.yearChange());
```
