### ISSUE TITLE
В классе CreditAccount не хватает ставки процента для расчета годового положительного баланса

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#14]
**Описание:**
В методе  yearChange в классе CreditAccount уравнение написано не полностью, в нем не хватает ставки процента для расчета нужных данных. 

**Локация дефекта:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

**Шаги воспроизведения:**
1.Создать экземпляр класса CreditAccount с начальным балансом 200, кредитным лимитом 15 .
2. Вызвать account.yearChange .

**Ожидаемый результат:** 
Ожидаемый результат должен получиться 0

**Фактический результат**:
Тест не проходит. 
 
**Тест**

    @Test
    public void testYearChangePositiveBalance() {
        CreditAccount account = new CreditAccount(200, 15, 0);
        assertEquals(0, account.yearChange());
    }

     

 **Окружение:**
Операционная система:

- Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
Дефект метода `yearChange()` класса `CreditAccount`:
Согласно требованиям начисление процентов должно производиться только в случае отрицательного текущего баланса. При положительном балансе проценты не начисляются.  В методе отсутствовала соответсвтующая проверка текущего баланса перед реализацией  вычисления процентов. Правильная реализация метода:
```
     public int yearChange() {
        if (balance < 0) {
            return (-balance / 100) * rate;
        } else {
            return 0;
        }
    }
```
