### ISSUE TITLE
Отрицательный баланс при выполнении операции оплаты в методе pay(int amount)

### ISSUE THREAD

**Issue by Spider-Dad** [Spider-Dad/javaqa_team_diplom_2#2]
##  Описание
В методе `pay(int amount)` класса `SavingAccount` происходит вычитание суммы покупки из баланса счета без проверки на отрицательный баланс

## Локация дефекта
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L48

## Шаги воспроизведения
1. Создать экземпляр класса `SavingAccount` с начальным балансом `1_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод `pay(int amount)` с заданной суммой покупки `3_000`.
3. Проверить результат уменьшения счета и значение баланса счета.

_Ожидаемый результат:_ Метод `pay` должен вернуть `false`, баланс счета должен остаться без изменений, равный `1_000`

_Фактический результат:_ Метод `pay` возвращает `true`, что указывает на успешное выполнение операции, несмотря на отрицательный баланс равный `-2000`

## Тест

```
@Test
    public void shouldNotPayBeyondBalance() {
        SavingAccount account = new SavingAccount(
                1_000,
                1_000,
                10_000,
                5
        );

        boolean result = account.pay(3_000);

        Assertions.assertFalse(result);
        Assertions.assertEquals(1_000, account.getBalance());
    }
```

## Окружение
- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
@OndineVIP посмотри этот ussue

**Comment by OndineVIP** [comment]
Для проверки на минимальный баланс до вычитания суммы покупки нужно использовать  if  и  перед вычитанием суммы покупки, необходимо проверить, что результат вычитания не будет отрицательным. 
Override
public boolean pay(int amount) {
    if (amount <= 0) {
        return false;
    }
    if (balance - amount < minBalance) {
        return false;
    }
    balance = balance - amount;
    return true;
}
