### ISSUE TITLE
 Непополнение счета при достижении максимального значения баланса в методе add (int amount)

### ISSUE THREAD

**Issue by Spider-Dad** [Spider-Dad/javaqa_team_diplom_2#3]
##  Описание
В методе `add(int amount)` класса `SavingAccount` обнаружена ошибка в логике, которая приводит к непополнению счета при достижении максимального значения. 

**Примечание**: исправление данной проблемы следует проводить после решения Issue #1, связанного с присваиванием значения суммы пополнения вместо увеличения баланса.

## Локация дефекта
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72

## Шаги воспроизведениия
1. Создать экземпляр класса `SavingAccount` с начальным балансом `2_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод `add(int amount)` с заданной суммой пополнения `8_000`.
3. Проверить результат пополнения счета и значение баланса счета.

_Ожидаемый результат:_ баланс счета должен быть увеличен до максимального значения `10_000` после пополнения счета.

_Фактический результат:_ баланс счета остается равным `2_000`, пополнение счета не происходит при достижении максимального значения.

## Тест
```
@Test
    public void shouldAddEqualsMaxBalance() {
        SavingAccount account = new SavingAccount(
                2_000,
                1_000,
                10_000,
                5
        );

        account.add(8_000);

        Assertions.assertEquals(2_000 + 8_000, account.getBalance());
    }
```
## Окружение

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
@OndineVIP посмотри этот Issue. Обрати внимание на примечание в описании

**Comment by OndineVIP** [comment]
При добавлении суммы на баланс, проверяется только, что новый баланс не будет превышать максимально разрешенный, но не происходит проверка на то, что в результате добавления баланс не превысит максимальный баланс.
Для того, чтобы исправить эту ошибку, можно дополнить код проверкой на то, что при добавлении суммы к текущему балансу, полученный результат не превышает максимальный баланс:
if (balance + amount <= maxBalance)
