### ISSUE TITLE
Неуменьшение счета при покупке при достижении минимального значения в методе pay(int amount)

### ISSUE THREAD

**Issue by Spider-Dad** [Spider-Dad/javaqa_team_diplom_2#4]
## Описание
В методе `pay(int amount)` класса `SavingAccount` обнаружена ошибка в логике, которая приводит к неуменьшению баланса при покупке, когда баланс достигает минимального значения.

## Локация дефекта
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49

## Шаги воспроизведения
1. Создать экземпляр класса `SavingAccount` с начальным балансом `5_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод pay(int amount) с заданной суммой покупки `4_000`.
3. Проверить результат уменьшения счета и значение баланса счета.

_Ожидаемый результат:_  метод `pay` должен вернуть `true`, баланс счета должен уменьшиться, стать равный `1_000`

_Фактический результат:_  метод `pay` возвращает `false`, что указывает на неуспешное выполнение операции, баланс счета остался без изменений, равный `5_000`

## Тест
```
@Test
    public void shouldPayEqualsMinBalance() {
        SavingAccount account = new SavingAccount(
                5_000,
                1_000,
                10_000,
                5
        );

        boolean result = account.pay(4_000);

        Assertions.assertTrue(result);
        Assertions.assertEquals(5_000 - 4_000, account.getBalance());
    }
```
## Окружение

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
@OndineVIP посмотри этот Issue

**Comment by OndineVIP** [comment]
ошибка возникает из-за того, что при списании денег с баланса, не выполняется проверка на достижение минимального порогового значения (minBalance). В коде метода pay(), если баланс становится меньше или равен minBalance, то метод возвращает false, что означает возможность списания со счета определенной суммы. Однако в тесте, значение списываемой суммы равно 4_000, что превышает минимальный пороговый баланс в 1_000, а значит метод pay() должен возвращать false. 

исправление: 
```
@Override
public boolean pay(int amount) {
    if (amount <= 0 || balance - amount < minBalance) {
        return false;
    }
    balance = balance - amount;
    return true;
}
