### ISSUE TITLE
Не выбрасывается исключение при параметрах SavingAccount конструктора MinBalance > MaxBalance

### ISSUE THREAD

**Issue by Spider-Dad** [Spider-Dad/javaqa_team_diplom_2#5]
## Описание
При создании объекта класса `SavingAccount` с некорректными параметрами, где минимальный баланс больше максимального, не выбрасывается исключение `IllegalArgumentException`, хотя по логке требуется, чтобы такие параметры вызывали исключение.
## Локация дефекта
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
## Шаги воспроизведения
1. Попытаться создать объект класса `SavingAccount` с параметрами: `initialBalance = 5_000`, `minBalance = 2_000`, `maxBalance = 1_000`, `rate = 5`.

_Ожидаемый результат:_ при создании объекта должно выбрасываться исключение `IllegalArgumentException` с соответствующим сообщением о некорректных параметрах.

_Фактический результат:_ исключение `IllegalArgumentException` не выбрасывается, и объект создается без ошибок.

## Тест
```
 @Test
    public void testIllegalArgumentExceptionMinBalanceMoreMaxBalance (){
        Assertions.assertThrows(IllegalArgumentException.class, () -> new SavingAccount(5_000,2_000,1_000,5));
    }
```
## Окружение

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
@OndineVIP посмотри этот Issue

**Comment by OndineVIP** [comment]
необходимо добавить проверку на минимальный баланс и выбросить исключение в случае, если он больше максимального значения:

```
public SavingAccount(int initialBalance, int minBalance, int maxBalance, int rate) {
    if (rate < 0) {
        throw new IllegalArgumentException("Накопительная ставка не может быть отрицательной, а у вас: " + rate);
    }
    if (minBalance > maxBalance) {
        throw new IllegalArgumentException("Начальный баланс не может быть больше максимального значения: " + initialBalance);
    }
    this.balance = initialBalance;
    this.minBalance = minBalance;
    this.maxBalance = maxBalance;
    this.rate = rate;
}
