### ISSUE TITLE
Не выбрасывается исключение при начальном балансе больше максимального баланса

### ISSUE THREAD

**Issue by Spider-Dad** [Spider-Dad/javaqa_team_diplom_2#7]
## Описание
При создании объекта класса `SavingAccount` с некорректными параметрами, где начальный баланс больше максимального, не выбрасывается исключение `IllegalArgumentException`, хотя по логике требуется, чтобы такие параметры вызывали исключение.
## Локация дефекта
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/2d1454bb38575ecd18a33533e5656be8067e387e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
## Шаги всопроизведения
1. Попытаться создать объект класса `SavingAccount` с параметрами: `initialBalance = 15_000`, `minBalance = 1_000`, `maxBalance = 10_000`, `rate = 5`.

Ожидаемый результат: при создании объекта должно выбрасываться исключение `IllegalArgumentException` с соответствующим сообщением о некорректных параметрах.

Фактический результат: исключение `IllegalArgumentException` не выбрасывается, и объект создается без ошибок.
## Тест
```
@Test
    public void testIllegalArgumentExceptionInitialBalanceMoreMaxBalance (){
        Assertions.assertThrows(IllegalArgumentException.class, () -> new SavingAccount(15_000,1_000,10_000,5));
    }
```
## Окружение

- Операционная система: Windows 11
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
@OndineVIP  посмотри этот Issue

**Comment by OndineVIP** [comment]
необходимо добавить проверку на начальный баланс и выбросить исключение в случае, если он больше максимального значения:

```
public SavingAccount(int initialBalance, int minBalance, int maxBalance, int rate) {
    if (rate < 0) {
        throw new IllegalArgumentException("Накопительная ставка не может быть отрицательной, а у вас: " + rate);
    }
    if (initialBalance > maxBalance) {
        throw new IllegalArgumentException("Начальный баланс не может быть больше  максимального значения: " + initialBalance);
    }
    this.balance = initialBalance;
    this.minBalance = minBalance;
    this.maxBalance = maxBalance;
    this.rate = rate;
}
