### ISSUE TITLE
Условие в CreditLimit заменяет текущее значение баланса на отрицательный баланс операции.

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#8]
**Описание:**
В классе creditLimit обнаружена ошибка.  Условие, которое устанавливает значение баланса (balance = -amount)не корректно, так как оно заменяет текущее значение баланса на отрицательный баланс операции, а не учитывает текущее значение баланса до операции.
**Локация дефекта :**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

**Шаги воспроизведения:**
1.Создать экземпляр класса CreditAccount  с начальным балансом 10_000, кредитным лимитом 15_000
2.Вызвать метод paybill(int amount) с заданной суммой списания в 1_000.
3.Проверить результат списания суммы с основного баланса.

**Ожидаемый результат:** метод account.pay должен уменьшить баланс счета на заданную сумму списания. Значение баланса счета после пополнения должно быть равно 9_000

**Фактический результат:** вместо уменьшения баланса на сумму списания счета, выводится сумма списания. 

**Тест:**
     @Test
    public void testValidPayment() {
        int initialBalance = 10_000;
        int creditLimit = 15_000;
        int amount = 1000;

        CreditAccount account = new CreditAccount(initialBalance, creditLimit, 10);
        boolean result = account.pay(1000);
        assertTrue(result);
        assertEquals(9000, account.getBalance());
    }

**Окружение:**

- Операционная система: Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
1. В строке "balance = -amount;" после проверки на превышение кредитного лимита должно быть "balance -= amount;", чтобы правильно уменьшить баланс.
2. Операция вычитания суммы покупки применена дважды. Оставить после проверки на превышение кредитного лимита.
