### ISSUE TITLE
В методе add значение поля balance присваивается только значение параметра amount

### ISSUE THREAD

**Issue by OndineVIP** [Spider-Dad/javaqa_team_diplom_2#9]
**Описание:**
В методе add класса CreditAccount значение поля balance присваивается только значение параметра amount, а не складывается с текущим балансом. Значит, при каждом вызове метода add старое значение баланса будет заменяться новым. 
**Локация дефекта:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/0830f9d49ed7f9a360bb858674cfba62cded9e5c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L70
**Шаги воспроизведения:**
1.Создать экземпляр класса CreditAccount с начальным балансом 10_000, кредитным лимитом 1_000 , сумма пополнения 2_000.
2.Вызвать метод account.add(int amount) с заданной суммой в 2_000.
3.Проверить результат пополнения суммы  основного баланса.

**Ожидаемый результат:** 
метод account.add(int amount) должен увеличить баланс счета на заданную сумму . Значение баланса счета после пополнения должно быть равно 12_000

**Фактический результат**:
 вместо увеличения баланса на сумму пополнения счета, выводится сумма списания. Это приводит к неправильному значению баланса, которое становится равным 2_000
 
**Тест:**
https://github.com/Spider-Dad/javaqa_team_diplom_2/blob/21b1e96de79b312551ec701b6451581902ccfd80/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L175

    @Test
    public void testAddWithValidAmount() {
        int initialBalance = 10_000;
        int creditLimit = 1000;

        CreditAccount account = new CreditAccount(initialBalance, creditLimit, 10);
        assertTrue(account.add(2000));
        assertEquals(12000, account.getBalance());
    }

    
   
 **Окружение:**
Операционная система: 
- Windows 10
- IDE: IntelliJ IDEA 2023.1 (Community Edition)
- Java: OpenJDK 11

**Comment by Spider-Dad** [comment]
Ошибка в методе `add()` класса `CreditAccount` следующая: вместо `balance = amount`  необходимо указать `balance += amount`
